### ISSUE TITLE
e30b558ea045eaea49a61a96d23ccd22a09c3fb1 should have been a pull request

### ISSUE THREAD

**Issue by jpivarski** [conda-forge/uproot-feedstock#34]
@chrisburr 

Yikes! That should have been a pull request. It's referencing this: scikit-hep/uproot#307. We're not depending on xxhash just yet, as the uproot PR has not been merged yet and we're still working on one issue. We really just need the xxhash dependency _before_ that, but due to my mistake using GitHub's web interface, it looks like it's already applied.

**Comment by chrisburr** [comment]
It all good, as you didn’t change the build number or version it didn’t deploy as the binary already existed on anaconda.org.

For future reference, updates have to be made on forks as all branches on the conda-forge repository try to deploy on every build (to allow multiple versions to be maintained in parallel if desired).
